# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b161a3837c7df9f2a3ffdf5d59852f9996b7f11fe6b79327a279f630c9101c8d9321767182e1acaa249d915c51e235a324a30772ab15875ca6a35103cdaa42a1

test:
  secret_key_base: 92be304423f31bd7f9459170ebf0864d27e2b5466c0f0c2089af6de16e140e5d83e5c8b0428cd9db5a1b80759a53b60b00b845df9aa93627a64483bdbeb9828a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
